services:
  library-app:
    build:
      context: .
    container_name: library-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-wispy-frog-a2nn74ds.eu-central-1.pg.koyeb.app/koyebdb
      SPRING_DATASOURCE_USERNAME: koyeb-adm
      SPRING_DATASOURCE_PASSWORD: pg_P6cW5jEXJAtZ
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: pg_P6cW5jEXJAtZ
      POSTGRES_DB: koyebdb
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ../frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://retired-vanda-glszen-ba299dbf.koyeb.app
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge